FROM dorgeln/orbiter:alpine-base-0.0.20

# For use on  mybinder.org please uncomment the following lines
# This isn't necessary for mybinder.org links generated with https://jupyterhub.github.io/nbgitpuller/link?tab=binder

# COPY . ${HOME}
# USER root
# RUN chown -R ${NB_UID} ${HOME}
# USER ${NB_USER}