#syntax=docker/dockerfile:1.2

FROM {{ docker_user }}/{{ docker_repo }}:stage-{{ version }} as stage

RUN find /env -name "*.pyc" -exec rm -f {} \; && \
    find /env -name "*.pyx" -exec rm -f {} \; && \
    find /env -name '*.a' -exec rm -f {} \; && \
    find /env -name '__pycache__' -type d -exec rm -rf '{}' '+'


FROM {{ docker_user }}/{{ docker_repo }}:core-{{ version }} as core

LABEL maintainer="{{ maintainer }}"

COPY --chown=${NB_USER} --from=stage /env  ${ENV_ROOT}

WORKDIR ${HOME}
CMD ["jupyter", "lab", "--ip", "0.0.0.0","--no-browser","--NotebookApp.token=''","--NotebookApp.password=''"]
EXPOSE 8888
