ARG VERSION={{ version }}
ARG DOCKER_USER={{ docker_user }}
ARG DOCKER_REPO={{ docker_repo }}

FROM ${DOCKER_USER}/${DOCKER_REPO}:core-${VERSION} as core

# RUN ${MAMBA_EXE} create -p ${MAMBA_ROOT_PREFIX}

COPY base.yml base.yml

RUN --mount=type=cache,id=mamba-pkgs,target=/env/mamba/pkgs,uid=1000,gid=100 \
    ${MAMBA_EXE} install -y -n base -f base.yml

# RUN ${MAMBA_EXE} create -y -f base.yml  -p ${MAMBA_ROOT_PREFIX}

# COPY mamba.pkg mamba.pkg
#RUN --mount=type=cache,id=mamba-pkgs,target=/env/mamba/pkgs,uid=1000,gid=100 \
#    PKG=`cat mamba.pkg` && \
#    echo Installing ${PKG} && \
#    ${MAMBA_EXE} install  ${PKG} -v -y -c conda-forge -p ${MAMBA_ROOT_PREFIX} 

