#syntax=docker/dockerfile:1.2

FROM {{ docker_user }}/{{ docker_repo }}:core-microm-{{ version }} as core

LABEL maintainer="{{ maintainer }}"

COPY base.yml base.yml

RUN --mount=type=cache,id=mamba-pkgs,target=/env/mamba/pkgs,uid={{ nb_uid }},gid={{ nb_gid }} \
    ${MAMBA_EXE} install -y -n base -f base.yml

